#!/usr/bin/ruby
require_relative './guesser.rb'
play = Guesser.new()
loop do
    print "Enter guess: "
    play.guess=(gets.strip)
    play.check_guess
    puts play.get_message
    break if (play.get_guess == play.secret?)
end
